CREATE TABLE ERROR_LOG (
    log_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_name   VARCHAR2(100),
    error_code    NUMBER,
    error_message VARCHAR2(4000),
    context_info  VARCHAR2(4000),
    log_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP
);
