CREATE TABLE AUDIT_LOG (
    audit_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name     VARCHAR2(100),
    action_type   VARCHAR2(20),   -- INSERT, UPDATE, DELETE
    table_name    VARCHAR2(50),
    attempt_time  TIMESTAMP DEFAULT SYSTIMESTAMP,
    status        VARCHAR2(20),   -- ALLOWED or DENIED
    reason        VARCHAR2(200)
);
